spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpa_board
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mvc:
    hidden-method:
      filter:
        enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
